// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: materials/testsupport.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.testsupport.input;

/**
 * Protobuf enum {@code gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.TestMaterialsProducerPropertyIdInput}
 */
public enum TestMaterialsProducerPropertyIdInput
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_1_BOOLEAN_MUTABLE_NO_TRACK = 0;</code>
   */
  MATERIALS_PRODUCER_PROPERTY_1_BOOLEAN_MUTABLE_NO_TRACK(0),
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_2_INTEGER_MUTABLE_NO_TRACK = 1;</code>
   */
  MATERIALS_PRODUCER_PROPERTY_2_INTEGER_MUTABLE_NO_TRACK(1),
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_3_DOUBLE_MUTABLE_NO_TRACK = 2;</code>
   */
  MATERIALS_PRODUCER_PROPERTY_3_DOUBLE_MUTABLE_NO_TRACK(2),
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_4_BOOLEAN_MUTABLE_TRACK = 3;</code>
   */
  MATERIALS_PRODUCER_PROPERTY_4_BOOLEAN_MUTABLE_TRACK(3),
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_5_INTEGER_MUTABLE_TRACK = 4;</code>
   */
  MATERIALS_PRODUCER_PROPERTY_5_INTEGER_MUTABLE_TRACK(4),
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_6_DOUBLE_MUTABLE_TRACK = 5;</code>
   */
  MATERIALS_PRODUCER_PROPERTY_6_DOUBLE_MUTABLE_TRACK(5),
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_7_BOOLEAN_IMMUTABLE_NO_TRACK = 6;</code>
   */
  MATERIALS_PRODUCER_PROPERTY_7_BOOLEAN_IMMUTABLE_NO_TRACK(6),
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_8_INTEGER_IMMUTABLE_NO_TRACK = 7;</code>
   */
  MATERIALS_PRODUCER_PROPERTY_8_INTEGER_IMMUTABLE_NO_TRACK(7),
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_9_DOUBLE_IMMUTABLE_NO_TRACK = 8;</code>
   */
  MATERIALS_PRODUCER_PROPERTY_9_DOUBLE_IMMUTABLE_NO_TRACK(8),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_1_BOOLEAN_MUTABLE_NO_TRACK = 0;</code>
   */
  public static final int MATERIALS_PRODUCER_PROPERTY_1_BOOLEAN_MUTABLE_NO_TRACK_VALUE = 0;
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_2_INTEGER_MUTABLE_NO_TRACK = 1;</code>
   */
  public static final int MATERIALS_PRODUCER_PROPERTY_2_INTEGER_MUTABLE_NO_TRACK_VALUE = 1;
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_3_DOUBLE_MUTABLE_NO_TRACK = 2;</code>
   */
  public static final int MATERIALS_PRODUCER_PROPERTY_3_DOUBLE_MUTABLE_NO_TRACK_VALUE = 2;
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_4_BOOLEAN_MUTABLE_TRACK = 3;</code>
   */
  public static final int MATERIALS_PRODUCER_PROPERTY_4_BOOLEAN_MUTABLE_TRACK_VALUE = 3;
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_5_INTEGER_MUTABLE_TRACK = 4;</code>
   */
  public static final int MATERIALS_PRODUCER_PROPERTY_5_INTEGER_MUTABLE_TRACK_VALUE = 4;
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_6_DOUBLE_MUTABLE_TRACK = 5;</code>
   */
  public static final int MATERIALS_PRODUCER_PROPERTY_6_DOUBLE_MUTABLE_TRACK_VALUE = 5;
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_7_BOOLEAN_IMMUTABLE_NO_TRACK = 6;</code>
   */
  public static final int MATERIALS_PRODUCER_PROPERTY_7_BOOLEAN_IMMUTABLE_NO_TRACK_VALUE = 6;
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_8_INTEGER_IMMUTABLE_NO_TRACK = 7;</code>
   */
  public static final int MATERIALS_PRODUCER_PROPERTY_8_INTEGER_IMMUTABLE_NO_TRACK_VALUE = 7;
  /**
   * <code>MATERIALS_PRODUCER_PROPERTY_9_DOUBLE_IMMUTABLE_NO_TRACK = 8;</code>
   */
  public static final int MATERIALS_PRODUCER_PROPERTY_9_DOUBLE_IMMUTABLE_NO_TRACK_VALUE = 8;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TestMaterialsProducerPropertyIdInput valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TestMaterialsProducerPropertyIdInput forNumber(int value) {
    switch (value) {
      case 0: return MATERIALS_PRODUCER_PROPERTY_1_BOOLEAN_MUTABLE_NO_TRACK;
      case 1: return MATERIALS_PRODUCER_PROPERTY_2_INTEGER_MUTABLE_NO_TRACK;
      case 2: return MATERIALS_PRODUCER_PROPERTY_3_DOUBLE_MUTABLE_NO_TRACK;
      case 3: return MATERIALS_PRODUCER_PROPERTY_4_BOOLEAN_MUTABLE_TRACK;
      case 4: return MATERIALS_PRODUCER_PROPERTY_5_INTEGER_MUTABLE_TRACK;
      case 5: return MATERIALS_PRODUCER_PROPERTY_6_DOUBLE_MUTABLE_TRACK;
      case 6: return MATERIALS_PRODUCER_PROPERTY_7_BOOLEAN_IMMUTABLE_NO_TRACK;
      case 7: return MATERIALS_PRODUCER_PROPERTY_8_INTEGER_IMMUTABLE_NO_TRACK;
      case 8: return MATERIALS_PRODUCER_PROPERTY_9_DOUBLE_IMMUTABLE_NO_TRACK;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TestMaterialsProducerPropertyIdInput>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TestMaterialsProducerPropertyIdInput> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TestMaterialsProducerPropertyIdInput>() {
          public TestMaterialsProducerPropertyIdInput findValueByNumber(int number) {
            return TestMaterialsProducerPropertyIdInput.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.testsupport.input.Testsupport.getDescriptor().getEnumTypes().get(3);
  }

  private static final TestMaterialsProducerPropertyIdInput[] VALUES = values();

  public static TestMaterialsProducerPropertyIdInput valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TestMaterialsProducerPropertyIdInput(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.TestMaterialsProducerPropertyIdInput)
}

