package plugins.reports;

import java.util.LinkedHashSet;
import java.util.Set;
import java.util.function.Consumer;
import java.util.function.Supplier;

import net.jcip.annotations.Immutable;
import nucleus.ActorContext;
import nucleus.PluginData;
import nucleus.PluginDataBuilder;
import nucleus.util.ContractException;
import plugins.reports.support.ReportError;

/**
 * An immutable container of the initial state of report actors. It contains: <BR>
 * <ul>
 * <li>report ids</li>
 * <li>suppliers of consumers of {@linkplain ReportContext} for report
 * initialization</li>
 * </ul>
 * 
 * @author Shawn Hatch
 *
 */
@Immutable
public final class ReportsPluginData implements PluginData {

	private static class Data {
		private Set<Supplier<Consumer<ActorContext>>> reports = new LinkedHashSet<>();

		public Data() {
		}

		public Data(Data data) {
			this.reports.addAll(data.reports);
		}
	}

	public final static Builder builder() {
		return new Builder(new Data());
	}

	public final static class Builder implements PluginDataBuilder {
		private Data data;

		private Builder(Data data) {
			this.data = data;
		}

		/**
		 * Returns the {@link ReportsInitialData} from the input collected by
		 * this builder. Clears the state of the builder.
		 */
		public ReportsPluginData build() {
			try {
				return new ReportsPluginData(data);
			} finally {
				data = new Data();
			}
		}

		/**
		 * Adds the report via its id and it initial behavior as supplied by the
		 * given supplier.
		 * 
		 * @throws ContractException
		 *             <li>{@linkplain ReportError#NULL_SUPPLIER} if the
		 *             supplier is null</li>
		 */
		public Builder addReport(Supplier<Consumer<ActorContext>> supplier) {
			
			if (supplier == null) {
				throw new ContractException(ReportError.NULL_SUPPLIER);
			}
			data.reports.add(supplier);
			return this;
		}

	}

	private final Data data;

	private ReportsPluginData(Data data) {
		this.data = data;
	}

	/**
	 * Returns the Consumer of ReportContext associated with the given report id
	 * 
	 * @throws ContractException
	 *             <li>{@linkplain ReportError#NULL_REPORT_ID} if the report id
	 *             is null</li>
	 *             <li>{@linkplain ReportError#UNKNOWN_REPORT_ID} if the report
	 *             id is unknown</li>
	 *             <li>{@linkplain ReportError#NULL_CONSUMER} if the consumer
	 *             generated by the supplier is null</li>
	 */
	public Set<Consumer<ActorContext>> getReports() {
		Set<Consumer<ActorContext>> result=  new LinkedHashSet<>();
		for(Supplier<Consumer<ActorContext>> supplier : data.reports) {
			result.add(	supplier.get());
		}
		return result;
	}

	@Override
	public PluginDataBuilder getCloneBuilder() {
		return new Builder(new Data(data));
	}

}
