// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input;

/**
 * Protobuf type {@code gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelMapInput}
 */
public final class PersonResourceLevelMapInput extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelMapInput)
    PersonResourceLevelMapInputOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PersonResourceLevelMapInput.newBuilder() to construct.
  private PersonResourceLevelMapInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PersonResourceLevelMapInput() {
    personResourceLevels_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PersonResourceLevelMapInput();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PersonResourceLevelMapInput_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PersonResourceLevelMapInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput.class, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput.Builder.class);
  }

  public static final int RESOURCEID_FIELD_NUMBER = 1;
  private gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput resourceId_;
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
   * @return Whether the resourceId field is set.
   */
  @java.lang.Override
  public boolean hasResourceId() {
    return resourceId_ != null;
  }
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
   * @return The resourceId.
   */
  @java.lang.Override
  public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput getResourceId() {
    return resourceId_ == null ? gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput.getDefaultInstance() : resourceId_;
  }
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
   */
  @java.lang.Override
  public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInputOrBuilder getResourceIdOrBuilder() {
    return resourceId_ == null ? gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput.getDefaultInstance() : resourceId_;
  }

  public static final int PERSONRESOURCELEVELS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput> personResourceLevels_;
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
   */
  @java.lang.Override
  public java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput> getPersonResourceLevelsList() {
    return personResourceLevels_;
  }
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInputOrBuilder> 
      getPersonResourceLevelsOrBuilderList() {
    return personResourceLevels_;
  }
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
   */
  @java.lang.Override
  public int getPersonResourceLevelsCount() {
    return personResourceLevels_.size();
  }
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
   */
  @java.lang.Override
  public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput getPersonResourceLevels(int index) {
    return personResourceLevels_.get(index);
  }
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
   */
  @java.lang.Override
  public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInputOrBuilder getPersonResourceLevelsOrBuilder(
      int index) {
    return personResourceLevels_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resourceId_ != null) {
      output.writeMessage(1, getResourceId());
    }
    for (int i = 0; i < personResourceLevels_.size(); i++) {
      output.writeMessage(2, personResourceLevels_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resourceId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResourceId());
    }
    for (int i = 0; i < personResourceLevels_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, personResourceLevels_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput)) {
      return super.equals(obj);
    }
    gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput other = (gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput) obj;

    if (hasResourceId() != other.hasResourceId()) return false;
    if (hasResourceId()) {
      if (!getResourceId()
          .equals(other.getResourceId())) return false;
    }
    if (!getPersonResourceLevelsList()
        .equals(other.getPersonResourceLevelsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResourceId()) {
      hash = (37 * hash) + RESOURCEID_FIELD_NUMBER;
      hash = (53 * hash) + getResourceId().hashCode();
    }
    if (getPersonResourceLevelsCount() > 0) {
      hash = (37 * hash) + PERSONRESOURCELEVELS_FIELD_NUMBER;
      hash = (53 * hash) + getPersonResourceLevelsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelMapInput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelMapInput)
      gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PersonResourceLevelMapInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PersonResourceLevelMapInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput.class, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput.Builder.class);
    }

    // Construct using gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      resourceId_ = null;
      if (resourceIdBuilder_ != null) {
        resourceIdBuilder_.dispose();
        resourceIdBuilder_ = null;
      }
      if (personResourceLevelsBuilder_ == null) {
        personResourceLevels_ = java.util.Collections.emptyList();
      } else {
        personResourceLevels_ = null;
        personResourceLevelsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PersonResourceLevelMapInput_descriptor;
    }

    @java.lang.Override
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput getDefaultInstanceForType() {
      return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput.getDefaultInstance();
    }

    @java.lang.Override
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput build() {
      gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput buildPartial() {
      gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput result = new gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput result) {
      if (personResourceLevelsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          personResourceLevels_ = java.util.Collections.unmodifiableList(personResourceLevels_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.personResourceLevels_ = personResourceLevels_;
      } else {
        result.personResourceLevels_ = personResourceLevelsBuilder_.build();
      }
    }

    private void buildPartial0(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.resourceId_ = resourceIdBuilder_ == null
            ? resourceId_
            : resourceIdBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput) {
        return mergeFrom((gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput other) {
      if (other == gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput.getDefaultInstance()) return this;
      if (other.hasResourceId()) {
        mergeResourceId(other.getResourceId());
      }
      if (personResourceLevelsBuilder_ == null) {
        if (!other.personResourceLevels_.isEmpty()) {
          if (personResourceLevels_.isEmpty()) {
            personResourceLevels_ = other.personResourceLevels_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePersonResourceLevelsIsMutable();
            personResourceLevels_.addAll(other.personResourceLevels_);
          }
          onChanged();
        }
      } else {
        if (!other.personResourceLevels_.isEmpty()) {
          if (personResourceLevelsBuilder_.isEmpty()) {
            personResourceLevelsBuilder_.dispose();
            personResourceLevelsBuilder_ = null;
            personResourceLevels_ = other.personResourceLevels_;
            bitField0_ = (bitField0_ & ~0x00000002);
            personResourceLevelsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPersonResourceLevelsFieldBuilder() : null;
          } else {
            personResourceLevelsBuilder_.addAllMessages(other.personResourceLevels_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getResourceIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput m =
                  input.readMessage(
                      gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput.parser(),
                      extensionRegistry);
              if (personResourceLevelsBuilder_ == null) {
                ensurePersonResourceLevelsIsMutable();
                personResourceLevels_.add(m);
              } else {
                personResourceLevelsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput resourceId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInputOrBuilder> resourceIdBuilder_;
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
     * @return Whether the resourceId field is set.
     */
    public boolean hasResourceId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
     * @return The resourceId.
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput getResourceId() {
      if (resourceIdBuilder_ == null) {
        return resourceId_ == null ? gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput.getDefaultInstance() : resourceId_;
      } else {
        return resourceIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
     */
    public Builder setResourceId(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput value) {
      if (resourceIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resourceId_ = value;
      } else {
        resourceIdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
     */
    public Builder setResourceId(
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput.Builder builderForValue) {
      if (resourceIdBuilder_ == null) {
        resourceId_ = builderForValue.build();
      } else {
        resourceIdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
     */
    public Builder mergeResourceId(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput value) {
      if (resourceIdBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          resourceId_ != null &&
          resourceId_ != gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput.getDefaultInstance()) {
          getResourceIdBuilder().mergeFrom(value);
        } else {
          resourceId_ = value;
        }
      } else {
        resourceIdBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
     */
    public Builder clearResourceId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      resourceId_ = null;
      if (resourceIdBuilder_ != null) {
        resourceIdBuilder_.dispose();
        resourceIdBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput.Builder getResourceIdBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getResourceIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInputOrBuilder getResourceIdOrBuilder() {
      if (resourceIdBuilder_ != null) {
        return resourceIdBuilder_.getMessageOrBuilder();
      } else {
        return resourceId_ == null ?
            gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput.getDefaultInstance() : resourceId_;
      }
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInputOrBuilder> 
        getResourceIdFieldBuilder() {
      if (resourceIdBuilder_ == null) {
        resourceIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInputOrBuilder>(
                getResourceId(),
                getParentForChildren(),
                isClean());
        resourceId_ = null;
      }
      return resourceIdBuilder_;
    }

    private java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput> personResourceLevels_ =
      java.util.Collections.emptyList();
    private void ensurePersonResourceLevelsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        personResourceLevels_ = new java.util.ArrayList<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput>(personResourceLevels_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInputOrBuilder> personResourceLevelsBuilder_;

    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput> getPersonResourceLevelsList() {
      if (personResourceLevelsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(personResourceLevels_);
      } else {
        return personResourceLevelsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public int getPersonResourceLevelsCount() {
      if (personResourceLevelsBuilder_ == null) {
        return personResourceLevels_.size();
      } else {
        return personResourceLevelsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput getPersonResourceLevels(int index) {
      if (personResourceLevelsBuilder_ == null) {
        return personResourceLevels_.get(index);
      } else {
        return personResourceLevelsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public Builder setPersonResourceLevels(
        int index, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput value) {
      if (personResourceLevelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonResourceLevelsIsMutable();
        personResourceLevels_.set(index, value);
        onChanged();
      } else {
        personResourceLevelsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public Builder setPersonResourceLevels(
        int index, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput.Builder builderForValue) {
      if (personResourceLevelsBuilder_ == null) {
        ensurePersonResourceLevelsIsMutable();
        personResourceLevels_.set(index, builderForValue.build());
        onChanged();
      } else {
        personResourceLevelsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public Builder addPersonResourceLevels(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput value) {
      if (personResourceLevelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonResourceLevelsIsMutable();
        personResourceLevels_.add(value);
        onChanged();
      } else {
        personResourceLevelsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public Builder addPersonResourceLevels(
        int index, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput value) {
      if (personResourceLevelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonResourceLevelsIsMutable();
        personResourceLevels_.add(index, value);
        onChanged();
      } else {
        personResourceLevelsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public Builder addPersonResourceLevels(
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput.Builder builderForValue) {
      if (personResourceLevelsBuilder_ == null) {
        ensurePersonResourceLevelsIsMutable();
        personResourceLevels_.add(builderForValue.build());
        onChanged();
      } else {
        personResourceLevelsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public Builder addPersonResourceLevels(
        int index, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput.Builder builderForValue) {
      if (personResourceLevelsBuilder_ == null) {
        ensurePersonResourceLevelsIsMutable();
        personResourceLevels_.add(index, builderForValue.build());
        onChanged();
      } else {
        personResourceLevelsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public Builder addAllPersonResourceLevels(
        java.lang.Iterable<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput> values) {
      if (personResourceLevelsBuilder_ == null) {
        ensurePersonResourceLevelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, personResourceLevels_);
        onChanged();
      } else {
        personResourceLevelsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public Builder clearPersonResourceLevels() {
      if (personResourceLevelsBuilder_ == null) {
        personResourceLevels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        personResourceLevelsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public Builder removePersonResourceLevels(int index) {
      if (personResourceLevelsBuilder_ == null) {
        ensurePersonResourceLevelsIsMutable();
        personResourceLevels_.remove(index);
        onChanged();
      } else {
        personResourceLevelsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput.Builder getPersonResourceLevelsBuilder(
        int index) {
      return getPersonResourceLevelsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInputOrBuilder getPersonResourceLevelsOrBuilder(
        int index) {
      if (personResourceLevelsBuilder_ == null) {
        return personResourceLevels_.get(index);  } else {
        return personResourceLevelsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public java.util.List<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInputOrBuilder> 
         getPersonResourceLevelsOrBuilderList() {
      if (personResourceLevelsBuilder_ != null) {
        return personResourceLevelsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(personResourceLevels_);
      }
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput.Builder addPersonResourceLevelsBuilder() {
      return getPersonResourceLevelsFieldBuilder().addBuilder(
          gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput.getDefaultInstance());
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput.Builder addPersonResourceLevelsBuilder(
        int index) {
      return getPersonResourceLevelsFieldBuilder().addBuilder(
          index, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput.getDefaultInstance());
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput personResourceLevels = 2;</code>
     */
    public java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput.Builder> 
         getPersonResourceLevelsBuilderList() {
      return getPersonResourceLevelsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInputOrBuilder> 
        getPersonResourceLevelsFieldBuilder() {
      if (personResourceLevelsBuilder_ == null) {
        personResourceLevelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelInputOrBuilder>(
                personResourceLevels_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        personResourceLevels_ = null;
      }
      return personResourceLevelsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelMapInput)
  }

  // @@protoc_insertion_point(class_scope:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelMapInput)
  private static final gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput();
  }

  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersonResourceLevelMapInput>
      PARSER = new com.google.protobuf.AbstractParser<PersonResourceLevelMapInput>() {
    @java.lang.Override
    public PersonResourceLevelMapInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PersonResourceLevelMapInput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PersonResourceLevelMapInput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.PersonResourceLevelMapInput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

