// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input;

public interface PersonResourceLevelInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonResourceLevelInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 personId = 1;</code>
   * @return The personId.
   */
  int getPersonId();

  /**
   * <code>int64 amount = 2;</code>
   * @return The amount.
   */
  long getAmount();
}
