// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input;

public interface ResourcePropertyValueMapInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourcePropertyValueMapInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
   * @return Whether the resourceId field is set.
   */
  boolean hasResourceId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
   * @return The resourceId.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInput getResourceId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ResourceIdInput resourceId = 1;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.resources.support.input.ResourceIdInputOrBuilder getResourceIdOrBuilder();

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput resourcePropertyValueMap = 2;</code>
   * @return Whether the resourcePropertyValueMap field is set.
   */
  boolean hasResourcePropertyValueMap();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput resourcePropertyValueMap = 2;</code>
   * @return The resourcePropertyValueMap.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput getResourcePropertyValueMap();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput resourcePropertyValueMap = 2;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInputOrBuilder getResourcePropertyValueMapOrBuilder();
}
