# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 10
    groups:
      standard-plugins:
        patterns:
          - "org.codehaus.mojo:flatten-maven-plugin"
          - "org.apache.maven.plugins*"
          - "org.sonatype.central"
      deploy-plugins:
        patterns:
          - "org.sonatype.central"
      dependencies:
        patterns:
          - "org.apache.commons:commons-math3"
          - "net.jcip:jcip-annotations"
          - "gov.hhs.aspr.ms.util"
      test-dependencies:
        patterns:
          - "org.jacoco*"
          - "org.junit.jupiter*"
