// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugins/globalproperties/data.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.globalproperties.data.input;

public interface GlobalPropertiesPluginDataInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GlobalPropertiesPluginDataInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionMapInput globalPropertyDefinitinions = 1;</code>
   */
  java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput> 
      getGlobalPropertyDefinitinionsList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionMapInput globalPropertyDefinitinions = 1;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput getGlobalPropertyDefinitinions(int index);
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionMapInput globalPropertyDefinitinions = 1;</code>
   */
  int getGlobalPropertyDefinitinionsCount();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionMapInput globalPropertyDefinitinions = 1;</code>
   */
  java.util.List<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInputOrBuilder> 
      getGlobalPropertyDefinitinionsOrBuilderList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionMapInput globalPropertyDefinitinions = 1;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInputOrBuilder getGlobalPropertyDefinitinionsOrBuilder(
      int index);

  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput globalPropertyValues = 2;</code>
   */
  java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput> 
      getGlobalPropertyValuesList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput globalPropertyValues = 2;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput getGlobalPropertyValues(int index);
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput globalPropertyValues = 2;</code>
   */
  int getGlobalPropertyValuesCount();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput globalPropertyValues = 2;</code>
   */
  java.util.List<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInputOrBuilder> 
      getGlobalPropertyValuesOrBuilderList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput globalPropertyValues = 2;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInputOrBuilder getGlobalPropertyValuesOrBuilder(
      int index);
}
