package plugins.stochastics;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;

import org.apache.commons.math3.random.RandomGenerator;
import org.junit.jupiter.api.Test;

import nucleus.DataManagerContext;
import plugins.stochastics.support.RandomNumberGeneratorId;
import plugins.stochastics.support.StochasticsError;
import plugins.stochastics.testsupport.StochasticsActionSupport;
import plugins.stochastics.testsupport.TestRandomGeneratorId;
import util.ContractException;
import util.annotations.UnitTest;
import util.annotations.UnitTestConstructor;
import util.annotations.UnitTestMethod;

@UnitTest(target = StochasticsDataManager.class)
public class AT_StochasticsDataManager {

	@Test
	@UnitTestMethod(name = "init", args = { DataManagerContext.class })
	public void testInit() {
		// nothing to test
	}

	@Test
	@UnitTestMethod(name = "getRandomNumberGeneratorIds", args = {})
	public void testGetRandomNumberGeneratorIds() {

		StochasticsActionSupport.testConsumer(2276874395058795370L, (c) -> {

			StochasticsDataManager stochasticsDataManager = c.getDataManager(StochasticsDataManager.class).get();

			Set<RandomNumberGeneratorId> actualRandomNumberGeneratorIds = stochasticsDataManager.getRandomNumberGeneratorIds();

			Set<TestRandomGeneratorId> expectedRandomGeneratorIds = new LinkedHashSet<>();
			for (TestRandomGeneratorId testRandomGeneratorId : TestRandomGeneratorId.values()) {
				expectedRandomGeneratorIds.add(testRandomGeneratorId);
			}
			assertEquals(expectedRandomGeneratorIds, actualRandomNumberGeneratorIds);
		});
	}

	@Test
	@UnitTestMethod(name = "getRandomGeneratorFromId", args = { RandomNumberGeneratorId.class })
	public void testGetRandomGeneratorFromId() {

		// show that random generators can be retrieved by ids
		StochasticsActionSupport.testConsumer(5489824520767978373L, (c) -> {
			StochasticsDataManager stochasticsDataManager = c.getDataManager(StochasticsDataManager.class).get();
			for (TestRandomGeneratorId testRandomGeneratorId : TestRandomGeneratorId.values()) {
				RandomGenerator randomGeneratorFromId = stochasticsDataManager.getRandomGeneratorFromId(testRandomGeneratorId);
				assertNotNull(randomGeneratorFromId);
			}
		});

		// precondition test : if the random number generator is null
		StochasticsActionSupport.testConsumer(5489824520767978373L, (c) -> {
			StochasticsDataManager stochasticsDataManager = c.getDataManager(StochasticsDataManager.class).get();
			ContractException contractException = assertThrows(ContractException.class, () -> stochasticsDataManager.getRandomGeneratorFromId(null));
			assertEquals(StochasticsError.NULL_RANDOM_NUMBER_GENERATOR_ID, contractException.getErrorType());
		});

		// precondition test : if the random number generator is unknown
		StochasticsActionSupport.testConsumer(2276874395058795370L, (c) -> {
			StochasticsDataManager stochasticsDataManager = c.getDataManager(StochasticsDataManager.class).get();
			ContractException contractException = assertThrows(ContractException.class,
					() -> stochasticsDataManager.getRandomGeneratorFromId(TestRandomGeneratorId.getUnknownRandomNumberGeneratorId()));
			assertEquals(StochasticsError.UNKNOWN_RANDOM_NUMBER_GENERATOR_ID, contractException.getErrorType());
		});

	}

	@Test
	@UnitTestMethod(name = "getRandomGenerator", args = {})
	public void testGetRandomGenerator() {
		// show that random generators can be retrieved by ids
		StochasticsActionSupport.testConsumer(683597885444214892L, (c) -> {
			StochasticsDataManager stochasticsDataManager = c.getDataManager(StochasticsDataManager.class).get();
			RandomGenerator randomGeneratorFromId = stochasticsDataManager.getRandomGenerator();
			assertNotNull(randomGeneratorFromId);
		});
	}

	@Test
	@UnitTestConstructor(args = { StochasticsPluginData.class })
	public void testConstructor() {
		// test of constructor is covered by the method tests
	}

	@Test
	@UnitTestMethod(name = "resetSeeds", args = { long.class })
	public void testResetSeeds() {

		StochasticsActionSupport.testConsumer(7392476210385850542L, (c) -> {

			StochasticsDataManager stochasticsDataManager = c.getDataManager(StochasticsDataManager.class).get();

			RandomGenerator randomGenerator = stochasticsDataManager.getRandomGenerator();

			long seed1 = randomGenerator.nextLong();

			long seed2 = randomGenerator.nextLong();

			/*
			 * Establish the first long generated by each random number
			 * generator after resetting the seed to seed1
			 */
			stochasticsDataManager.resetSeeds(seed1);

			randomGenerator = stochasticsDataManager.getRandomGenerator();
			long expectedGeneratorValue = randomGenerator.nextLong();

			Map<TestRandomGeneratorId, Long> expectedGeneratorValues = new LinkedHashMap<>();
			for (TestRandomGeneratorId testRandomGeneratorId : TestRandomGeneratorId.values()) {
				long value = stochasticsDataManager.getRandomGeneratorFromId(testRandomGeneratorId).nextLong();
				expectedGeneratorValues.put(testRandomGeneratorId, value);
			}

			/*
			 * re-seed to a new seed and show that the initial longs returned
			 * changed for all generators
			 */
			stochasticsDataManager.resetSeeds(seed2);
			randomGenerator = stochasticsDataManager.getRandomGenerator();

			assertNotEquals(expectedGeneratorValue, randomGenerator.nextLong());

			for (TestRandomGeneratorId testRandomGeneratorId : TestRandomGeneratorId.values()) {
				long value = stochasticsDataManager.getRandomGeneratorFromId(testRandomGeneratorId).nextLong();
				assertNotEquals(expectedGeneratorValues.get(testRandomGeneratorId), value);
			}

			/*
			 * re-seed to the original seed and show that the values are as they
			 * were
			 */
			stochasticsDataManager.resetSeeds(seed1);
			randomGenerator = stochasticsDataManager.getRandomGenerator();

			assertEquals(expectedGeneratorValue, randomGenerator.nextLong());

			for (TestRandomGeneratorId testRandomGeneratorId : TestRandomGeneratorId.values()) {
				long value = stochasticsDataManager.getRandomGeneratorFromId(testRandomGeneratorId).nextLong();
				assertEquals(expectedGeneratorValues.get(testRandomGeneratorId), value);
			}

		});

	}

}
