// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: regions/reports.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.regions.reports.input;

public interface RegionTransferReportPluginDataInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.RegionTransferReportPluginDataInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ReportLabelInput reportLabel = 1;</code>
   * @return Whether the reportLabel field is set.
   */
  boolean hasReportLabel();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ReportLabelInput reportLabel = 1;</code>
   * @return The reportLabel.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.reports.support.input.ReportLabelInput getReportLabel();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ReportLabelInput reportLabel = 1;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.reports.support.input.ReportLabelInputOrBuilder getReportLabelOrBuilder();

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ReportPeriodInput reportPeriod = 2;</code>
   * @return The enum numeric value on the wire for reportPeriod.
   */
  int getReportPeriodValue();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.ReportPeriodInput reportPeriod = 2;</code>
   * @return The reportPeriod.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.reports.support.input.ReportPeriodInput getReportPeriod();
}
