// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partitions/data.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.partitions.data.input;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PartitionsPluginDataInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PartitionsPluginDataInput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025partitions/data.proto\022+gov.hhs.aspr.ms" +
      ".gcm.taskit.protobuf.plugins\"9\n\031Partitio" +
      "nsPluginDataInput\022\034\n\024supportRunContinuit" +
      "y\030\001 \001(\010BE\nAgov.hhs.aspr.ms.gcm.taskit.pr" +
      "otobuf.plugins.partitions.data.inputP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PartitionsPluginDataInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PartitionsPluginDataInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PartitionsPluginDataInput_descriptor,
        new java.lang.String[] { "SupportRunContinuity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
