package plugins.components.support;

import util.ContractError;
import util.ContractException;

/**
 * An enumeration supporting {@link ContractException} that acts as a general
 * description of the exception.
 * 
 * @author Shawn Hatch
 *
 */
public enum ComponentError implements ContractError {

	COMPONENT_ID_ALREADY_EXISTS("Component id already exists in the simulation"),
	
	NULL_AGENT_INITIAL_BEHAVIOR_CONSUMER("Null agent initial behavior consumer"),
	
	NULL_AGENT_ID("Null agent id"),
	
	UNKNOWN_COMPONENT_ID("Unknown component id"), 
	
	AGENT_EXCLUSIVE_EVENT("Event generated by non-Agent was not expected"),
	
	RESOLVER_EXCLUSIVE_EVENT("Event generated by non-Resolver was not expected");
	

	private final String description;

	private ComponentError(final String description) {
		this.description = description;
	}

	@Override
	public String getDescription() {
		return description;
	}
}
