// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: materials/reports.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.reports.input;

public final class Reports {
  private Reports() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_BatchStatusReportPluginDataInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_BatchStatusReportPluginDataInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerPropertyReportPluginDataInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerPropertyReportPluginDataInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerResourceReportPluginDataInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerResourceReportPluginDataInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_StageReportPluginDataInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_StageReportPluginDataInput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027materials/reports.proto\022+gov.hhs.aspr." +
      "ms.gcm.taskit.protobuf.plugins\032\025reports/" +
      "support.proto\"v\n BatchStatusReportPlugin" +
      "DataInput\022R\n\013reportLabel\030\001 \001(\0132=.gov.hhs" +
      ".aspr.ms.gcm.taskit.protobuf.plugins.Rep" +
      "ortLabelInput\"\204\001\n.MaterialsProducerPrope" +
      "rtyReportPluginDataInput\022R\n\013reportLabel\030" +
      "\001 \001(\0132=.gov.hhs.aspr.ms.gcm.taskit.proto" +
      "buf.plugins.ReportLabelInput\"\204\001\n.Materia" +
      "lsProducerResourceReportPluginDataInput\022" +
      "R\n\013reportLabel\030\001 \001(\0132=.gov.hhs.aspr.ms.g" +
      "cm.taskit.protobuf.plugins.ReportLabelIn" +
      "put\"p\n\032StageReportPluginDataInput\022R\n\013rep" +
      "ortLabel\030\001 \001(\0132=.gov.hhs.aspr.ms.gcm.tas" +
      "kit.protobuf.plugins.ReportLabelInputBG\n" +
      "Cgov.hhs.aspr.ms.gcm.taskit.protobuf.plu" +
      "gins.materials.reports.inputP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.reports.support.input.Support.getDescriptor(),
        });
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_BatchStatusReportPluginDataInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_BatchStatusReportPluginDataInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_BatchStatusReportPluginDataInput_descriptor,
        new java.lang.String[] { "ReportLabel", });
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerPropertyReportPluginDataInput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerPropertyReportPluginDataInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerPropertyReportPluginDataInput_descriptor,
        new java.lang.String[] { "ReportLabel", });
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerResourceReportPluginDataInput_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerResourceReportPluginDataInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerResourceReportPluginDataInput_descriptor,
        new java.lang.String[] { "ReportLabel", });
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_StageReportPluginDataInput_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_StageReportPluginDataInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_StageReportPluginDataInput_descriptor,
        new java.lang.String[] { "ReportLabel", });
    gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.reports.support.input.Support.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
