// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: properties/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input;

/**
 * Protobuf type {@code gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionMapInput}
 */
public final class PropertyDefinitionMapInput extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionMapInput)
    PropertyDefinitionMapInputOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PropertyDefinitionMapInput.newBuilder() to construct.
  private PropertyDefinitionMapInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PropertyDefinitionMapInput() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PropertyDefinitionMapInput();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PropertyDefinitionMapInput_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PropertyDefinitionMapInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput.class, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput.Builder.class);
  }

  public static final int PROPERTYID_FIELD_NUMBER = 1;
  private com.google.protobuf.Any propertyId_;
  /**
   * <code>.google.protobuf.Any propertyId = 1;</code>
   * @return Whether the propertyId field is set.
   */
  @java.lang.Override
  public boolean hasPropertyId() {
    return propertyId_ != null;
  }
  /**
   * <code>.google.protobuf.Any propertyId = 1;</code>
   * @return The propertyId.
   */
  @java.lang.Override
  public com.google.protobuf.Any getPropertyId() {
    return propertyId_ == null ? com.google.protobuf.Any.getDefaultInstance() : propertyId_;
  }
  /**
   * <code>.google.protobuf.Any propertyId = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.AnyOrBuilder getPropertyIdOrBuilder() {
    return propertyId_ == null ? com.google.protobuf.Any.getDefaultInstance() : propertyId_;
  }

  public static final int PROPERTYDEFINITION_FIELD_NUMBER = 2;
  private gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput propertyDefinition_;
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionInput propertyDefinition = 2;</code>
   * @return Whether the propertyDefinition field is set.
   */
  @java.lang.Override
  public boolean hasPropertyDefinition() {
    return propertyDefinition_ != null;
  }
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionInput propertyDefinition = 2;</code>
   * @return The propertyDefinition.
   */
  @java.lang.Override
  public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput getPropertyDefinition() {
    return propertyDefinition_ == null ? gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput.getDefaultInstance() : propertyDefinition_;
  }
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionInput propertyDefinition = 2;</code>
   */
  @java.lang.Override
  public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInputOrBuilder getPropertyDefinitionOrBuilder() {
    return propertyDefinition_ == null ? gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput.getDefaultInstance() : propertyDefinition_;
  }

  public static final int PROPERTYDEFINITIONTIME_FIELD_NUMBER = 3;
  private double propertyDefinitionTime_ = 0D;
  /**
   * <code>double propertyDefinitionTime = 3;</code>
   * @return The propertyDefinitionTime.
   */
  @java.lang.Override
  public double getPropertyDefinitionTime() {
    return propertyDefinitionTime_;
  }

  public static final int PROPERTYTRACKINGPOLICY_FIELD_NUMBER = 4;
  private boolean propertyTrackingPolicy_ = false;
  /**
   * <code>bool propertyTrackingPolicy = 4;</code>
   * @return The propertyTrackingPolicy.
   */
  @java.lang.Override
  public boolean getPropertyTrackingPolicy() {
    return propertyTrackingPolicy_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (propertyId_ != null) {
      output.writeMessage(1, getPropertyId());
    }
    if (propertyDefinition_ != null) {
      output.writeMessage(2, getPropertyDefinition());
    }
    if (java.lang.Double.doubleToRawLongBits(propertyDefinitionTime_) != 0) {
      output.writeDouble(3, propertyDefinitionTime_);
    }
    if (propertyTrackingPolicy_ != false) {
      output.writeBool(4, propertyTrackingPolicy_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (propertyId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPropertyId());
    }
    if (propertyDefinition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPropertyDefinition());
    }
    if (java.lang.Double.doubleToRawLongBits(propertyDefinitionTime_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, propertyDefinitionTime_);
    }
    if (propertyTrackingPolicy_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, propertyTrackingPolicy_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput)) {
      return super.equals(obj);
    }
    gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput other = (gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput) obj;

    if (hasPropertyId() != other.hasPropertyId()) return false;
    if (hasPropertyId()) {
      if (!getPropertyId()
          .equals(other.getPropertyId())) return false;
    }
    if (hasPropertyDefinition() != other.hasPropertyDefinition()) return false;
    if (hasPropertyDefinition()) {
      if (!getPropertyDefinition()
          .equals(other.getPropertyDefinition())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getPropertyDefinitionTime())
        != java.lang.Double.doubleToLongBits(
            other.getPropertyDefinitionTime())) return false;
    if (getPropertyTrackingPolicy()
        != other.getPropertyTrackingPolicy()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPropertyId()) {
      hash = (37 * hash) + PROPERTYID_FIELD_NUMBER;
      hash = (53 * hash) + getPropertyId().hashCode();
    }
    if (hasPropertyDefinition()) {
      hash = (37 * hash) + PROPERTYDEFINITION_FIELD_NUMBER;
      hash = (53 * hash) + getPropertyDefinition().hashCode();
    }
    hash = (37 * hash) + PROPERTYDEFINITIONTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPropertyDefinitionTime()));
    hash = (37 * hash) + PROPERTYTRACKINGPOLICY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPropertyTrackingPolicy());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionMapInput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionMapInput)
      gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PropertyDefinitionMapInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PropertyDefinitionMapInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput.class, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput.Builder.class);
    }

    // Construct using gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      propertyId_ = null;
      if (propertyIdBuilder_ != null) {
        propertyIdBuilder_.dispose();
        propertyIdBuilder_ = null;
      }
      propertyDefinition_ = null;
      if (propertyDefinitionBuilder_ != null) {
        propertyDefinitionBuilder_.dispose();
        propertyDefinitionBuilder_ = null;
      }
      propertyDefinitionTime_ = 0D;
      propertyTrackingPolicy_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_PropertyDefinitionMapInput_descriptor;
    }

    @java.lang.Override
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput getDefaultInstanceForType() {
      return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput.getDefaultInstance();
    }

    @java.lang.Override
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput build() {
      gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput buildPartial() {
      gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput result = new gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.propertyId_ = propertyIdBuilder_ == null
            ? propertyId_
            : propertyIdBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.propertyDefinition_ = propertyDefinitionBuilder_ == null
            ? propertyDefinition_
            : propertyDefinitionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.propertyDefinitionTime_ = propertyDefinitionTime_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.propertyTrackingPolicy_ = propertyTrackingPolicy_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput) {
        return mergeFrom((gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput other) {
      if (other == gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput.getDefaultInstance()) return this;
      if (other.hasPropertyId()) {
        mergePropertyId(other.getPropertyId());
      }
      if (other.hasPropertyDefinition()) {
        mergePropertyDefinition(other.getPropertyDefinition());
      }
      if (other.getPropertyDefinitionTime() != 0D) {
        setPropertyDefinitionTime(other.getPropertyDefinitionTime());
      }
      if (other.getPropertyTrackingPolicy() != false) {
        setPropertyTrackingPolicy(other.getPropertyTrackingPolicy());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getPropertyIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPropertyDefinitionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              propertyDefinitionTime_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 32: {
              propertyTrackingPolicy_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Any propertyId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> propertyIdBuilder_;
    /**
     * <code>.google.protobuf.Any propertyId = 1;</code>
     * @return Whether the propertyId field is set.
     */
    public boolean hasPropertyId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Any propertyId = 1;</code>
     * @return The propertyId.
     */
    public com.google.protobuf.Any getPropertyId() {
      if (propertyIdBuilder_ == null) {
        return propertyId_ == null ? com.google.protobuf.Any.getDefaultInstance() : propertyId_;
      } else {
        return propertyIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Any propertyId = 1;</code>
     */
    public Builder setPropertyId(com.google.protobuf.Any value) {
      if (propertyIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        propertyId_ = value;
      } else {
        propertyIdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Any propertyId = 1;</code>
     */
    public Builder setPropertyId(
        com.google.protobuf.Any.Builder builderForValue) {
      if (propertyIdBuilder_ == null) {
        propertyId_ = builderForValue.build();
      } else {
        propertyIdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Any propertyId = 1;</code>
     */
    public Builder mergePropertyId(com.google.protobuf.Any value) {
      if (propertyIdBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          propertyId_ != null &&
          propertyId_ != com.google.protobuf.Any.getDefaultInstance()) {
          getPropertyIdBuilder().mergeFrom(value);
        } else {
          propertyId_ = value;
        }
      } else {
        propertyIdBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Any propertyId = 1;</code>
     */
    public Builder clearPropertyId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      propertyId_ = null;
      if (propertyIdBuilder_ != null) {
        propertyIdBuilder_.dispose();
        propertyIdBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Any propertyId = 1;</code>
     */
    public com.google.protobuf.Any.Builder getPropertyIdBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getPropertyIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Any propertyId = 1;</code>
     */
    public com.google.protobuf.AnyOrBuilder getPropertyIdOrBuilder() {
      if (propertyIdBuilder_ != null) {
        return propertyIdBuilder_.getMessageOrBuilder();
      } else {
        return propertyId_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : propertyId_;
      }
    }
    /**
     * <code>.google.protobuf.Any propertyId = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getPropertyIdFieldBuilder() {
      if (propertyIdBuilder_ == null) {
        propertyIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getPropertyId(),
                getParentForChildren(),
                isClean());
        propertyId_ = null;
      }
      return propertyIdBuilder_;
    }

    private gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput propertyDefinition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInputOrBuilder> propertyDefinitionBuilder_;
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionInput propertyDefinition = 2;</code>
     * @return Whether the propertyDefinition field is set.
     */
    public boolean hasPropertyDefinition() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionInput propertyDefinition = 2;</code>
     * @return The propertyDefinition.
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput getPropertyDefinition() {
      if (propertyDefinitionBuilder_ == null) {
        return propertyDefinition_ == null ? gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput.getDefaultInstance() : propertyDefinition_;
      } else {
        return propertyDefinitionBuilder_.getMessage();
      }
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionInput propertyDefinition = 2;</code>
     */
    public Builder setPropertyDefinition(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput value) {
      if (propertyDefinitionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        propertyDefinition_ = value;
      } else {
        propertyDefinitionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionInput propertyDefinition = 2;</code>
     */
    public Builder setPropertyDefinition(
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput.Builder builderForValue) {
      if (propertyDefinitionBuilder_ == null) {
        propertyDefinition_ = builderForValue.build();
      } else {
        propertyDefinitionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionInput propertyDefinition = 2;</code>
     */
    public Builder mergePropertyDefinition(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput value) {
      if (propertyDefinitionBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          propertyDefinition_ != null &&
          propertyDefinition_ != gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput.getDefaultInstance()) {
          getPropertyDefinitionBuilder().mergeFrom(value);
        } else {
          propertyDefinition_ = value;
        }
      } else {
        propertyDefinitionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionInput propertyDefinition = 2;</code>
     */
    public Builder clearPropertyDefinition() {
      bitField0_ = (bitField0_ & ~0x00000002);
      propertyDefinition_ = null;
      if (propertyDefinitionBuilder_ != null) {
        propertyDefinitionBuilder_.dispose();
        propertyDefinitionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionInput propertyDefinition = 2;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput.Builder getPropertyDefinitionBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPropertyDefinitionFieldBuilder().getBuilder();
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionInput propertyDefinition = 2;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInputOrBuilder getPropertyDefinitionOrBuilder() {
      if (propertyDefinitionBuilder_ != null) {
        return propertyDefinitionBuilder_.getMessageOrBuilder();
      } else {
        return propertyDefinition_ == null ?
            gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput.getDefaultInstance() : propertyDefinition_;
      }
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionInput propertyDefinition = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInputOrBuilder> 
        getPropertyDefinitionFieldBuilder() {
      if (propertyDefinitionBuilder_ == null) {
        propertyDefinitionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionInputOrBuilder>(
                getPropertyDefinition(),
                getParentForChildren(),
                isClean());
        propertyDefinition_ = null;
      }
      return propertyDefinitionBuilder_;
    }

    private double propertyDefinitionTime_ ;
    /**
     * <code>double propertyDefinitionTime = 3;</code>
     * @return The propertyDefinitionTime.
     */
    @java.lang.Override
    public double getPropertyDefinitionTime() {
      return propertyDefinitionTime_;
    }
    /**
     * <code>double propertyDefinitionTime = 3;</code>
     * @param value The propertyDefinitionTime to set.
     * @return This builder for chaining.
     */
    public Builder setPropertyDefinitionTime(double value) {
      
      propertyDefinitionTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double propertyDefinitionTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPropertyDefinitionTime() {
      bitField0_ = (bitField0_ & ~0x00000004);
      propertyDefinitionTime_ = 0D;
      onChanged();
      return this;
    }

    private boolean propertyTrackingPolicy_ ;
    /**
     * <code>bool propertyTrackingPolicy = 4;</code>
     * @return The propertyTrackingPolicy.
     */
    @java.lang.Override
    public boolean getPropertyTrackingPolicy() {
      return propertyTrackingPolicy_;
    }
    /**
     * <code>bool propertyTrackingPolicy = 4;</code>
     * @param value The propertyTrackingPolicy to set.
     * @return This builder for chaining.
     */
    public Builder setPropertyTrackingPolicy(boolean value) {
      
      propertyTrackingPolicy_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool propertyTrackingPolicy = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPropertyTrackingPolicy() {
      bitField0_ = (bitField0_ & ~0x00000008);
      propertyTrackingPolicy_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionMapInput)
  }

  // @@protoc_insertion_point(class_scope:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyDefinitionMapInput)
  private static final gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput();
  }

  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PropertyDefinitionMapInput>
      PARSER = new com.google.protobuf.AbstractParser<PropertyDefinitionMapInput>() {
    @java.lang.Override
    public PropertyDefinitionMapInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PropertyDefinitionMapInput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PropertyDefinitionMapInput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyDefinitionMapInput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

