// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partitions/testsupport.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.partitions.testsupport.input;

public interface TestLabelerInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.TestLabelerInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
