// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partitions/testsupport.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.partitions.testsupport.input;

public final class Testsupport {
  private Testsupport() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_TestFilterInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_TestFilterInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_TestLabelerInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_TestLabelerInput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034partitions/testsupport.proto\022+gov.hhs." +
      "aspr.ms.gcm.taskit.protobuf.plugins\"#\n\017T" +
      "estFilterInput\022\020\n\010filterId\030\001 \001(\005\"\036\n\020Test" +
      "LabelerInput\022\n\n\002id\030\001 \001(\t*f\n\024TestAttribut" +
      "eIdInput\022\t\n\005INT_0\020\000\022\t\n\005INT_1\020\001\022\014\n\010DOUBLE" +
      "_0\020\002\022\014\n\010DOUBLE_1\020\003\022\r\n\tBOOLEAN_0\020\004\022\r\n\tBOO" +
      "LEAN_1\020\005BL\nHgov.hhs.aspr.ms.gcm.taskit.p" +
      "rotobuf.plugins.partitions.testsupport.i" +
      "nputP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_TestFilterInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_TestFilterInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_TestFilterInput_descriptor,
        new java.lang.String[] { "FilterId", });
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_TestLabelerInput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_TestLabelerInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_TestLabelerInput_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
