// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: groups/testsupport.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.testsupport.input;

/**
 * Protobuf enum {@code gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.TestGroupTypeIdInput}
 */
public enum TestGroupTypeIdInput
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>GROUP_TYPE_1 = 0;</code>
   */
  GROUP_TYPE_1(0),
  /**
   * <code>GROUP_TYPE_2 = 1;</code>
   */
  GROUP_TYPE_2(1),
  /**
   * <code>GROUP_TYPE_3 = 2;</code>
   */
  GROUP_TYPE_3(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>GROUP_TYPE_1 = 0;</code>
   */
  public static final int GROUP_TYPE_1_VALUE = 0;
  /**
   * <code>GROUP_TYPE_2 = 1;</code>
   */
  public static final int GROUP_TYPE_2_VALUE = 1;
  /**
   * <code>GROUP_TYPE_3 = 2;</code>
   */
  public static final int GROUP_TYPE_3_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TestGroupTypeIdInput valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TestGroupTypeIdInput forNumber(int value) {
    switch (value) {
      case 0: return GROUP_TYPE_1;
      case 1: return GROUP_TYPE_2;
      case 2: return GROUP_TYPE_3;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TestGroupTypeIdInput>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TestGroupTypeIdInput> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TestGroupTypeIdInput>() {
          public TestGroupTypeIdInput findValueByNumber(int number) {
            return TestGroupTypeIdInput.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.testsupport.input.Testsupport.getDescriptor().getEnumTypes().get(0);
  }

  private static final TestGroupTypeIdInput[] VALUES = values();

  public static TestGroupTypeIdInput valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TestGroupTypeIdInput(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.TestGroupTypeIdInput)
}

