// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partitions/filters.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.partitions.support.filters.input;

public interface NotFilterInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.NotFilterInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.FilterInput a = 1;</code>
   * @return Whether the a field is set.
   */
  boolean hasA();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.FilterInput a = 1;</code>
   * @return The a.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.partitions.support.filters.input.FilterInput getA();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.FilterInput a = 1;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.partitions.support.filters.input.FilterInputOrBuilder getAOrBuilder();
}
