// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partitions/filters.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.partitions.support.filters.input;

public interface TrueFilterInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.TrueFilterInput)
    com.google.protobuf.MessageOrBuilder {
}
