// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personproperties/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.personproperties.support.input;

public interface PersonPropertyDimensionInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonPropertyDimensionInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonPropertyIdInput personPropertyId = 1;</code>
   * @return Whether the personPropertyId field is set.
   */
  boolean hasPersonPropertyId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonPropertyIdInput personPropertyId = 1;</code>
   * @return The personPropertyId.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.personproperties.support.input.PersonPropertyIdInput getPersonPropertyId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonPropertyIdInput personPropertyId = 1;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.personproperties.support.input.PersonPropertyIdInputOrBuilder getPersonPropertyIdOrBuilder();

  /**
   * <code>bool trackTimes = 2;</code>
   * @return The trackTimes.
   */
  boolean getTrackTimes();

  /**
   * <code>repeated .google.protobuf.Any values = 3;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getValuesList();
  /**
   * <code>repeated .google.protobuf.Any values = 3;</code>
   */
  com.google.protobuf.Any getValues(int index);
  /**
   * <code>repeated .google.protobuf.Any values = 3;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .google.protobuf.Any values = 3;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Any values = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getValuesOrBuilder(
      int index);
}
