// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: regions/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.regions.support.input;

public interface RegionMembershipInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.RegionMembershipInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.RegionIdInput regionId = 1;</code>
   * @return Whether the regionId field is set.
   */
  boolean hasRegionId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.RegionIdInput regionId = 1;</code>
   * @return The regionId.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.regions.support.input.RegionIdInput getRegionId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.RegionIdInput regionId = 1;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.regions.support.input.RegionIdInputOrBuilder getRegionIdOrBuilder();

  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.RegionMembershipInput.RegionPersonInfo people = 2;</code>
   */
  java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.regions.support.input.RegionMembershipInput.RegionPersonInfo> 
      getPeopleList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.RegionMembershipInput.RegionPersonInfo people = 2;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.regions.support.input.RegionMembershipInput.RegionPersonInfo getPeople(int index);
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.RegionMembershipInput.RegionPersonInfo people = 2;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.RegionMembershipInput.RegionPersonInfo people = 2;</code>
   */
  java.util.List<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.regions.support.input.RegionMembershipInput.RegionPersonInfoOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.RegionMembershipInput.RegionPersonInfo people = 2;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.regions.support.input.RegionMembershipInput.RegionPersonInfoOrBuilder getPeopleOrBuilder(
      int index);
}
