// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stochastics/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.stochastics.support.input;

public interface RandomNumberGeneratorMapInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.RandomNumberGeneratorMapInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.RandomNumberGeneratorIdInput randomNumberGeneratorId = 1;</code>
   * @return Whether the randomNumberGeneratorId field is set.
   */
  boolean hasRandomNumberGeneratorId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.RandomNumberGeneratorIdInput randomNumberGeneratorId = 1;</code>
   * @return The randomNumberGeneratorId.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.stochastics.support.input.RandomNumberGeneratorIdInput getRandomNumberGeneratorId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.RandomNumberGeneratorIdInput randomNumberGeneratorId = 1;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.stochastics.support.input.RandomNumberGeneratorIdInputOrBuilder getRandomNumberGeneratorIdOrBuilder();

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.WellStateInput wellState = 2;</code>
   * @return Whether the wellState field is set.
   */
  boolean hasWellState();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.WellStateInput wellState = 2;</code>
   * @return The wellState.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.stochastics.support.input.WellStateInput getWellState();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.WellStateInput wellState = 2;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.stochastics.support.input.WellStateInputOrBuilder getWellStateOrBuilder();
}
