// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.people.support.input;

public interface PersonRangeInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonRangeInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 lowPersonId = 1;</code>
   * @return The lowPersonId.
   */
  int getLowPersonId();

  /**
   * <code>int32 highPersonId = 2;</code>
   * @return The highPersonId.
   */
  int getHighPersonId();
}
