// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.people.support.input;

public interface PersonIdInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonIdInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
