// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: materials/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input;

/**
 * Protobuf type {@code gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerPropertyValueMapInput}
 */
public final class MaterialsProducerPropertyValueMapInput extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerPropertyValueMapInput)
    MaterialsProducerPropertyValueMapInputOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MaterialsProducerPropertyValueMapInput.newBuilder() to construct.
  private MaterialsProducerPropertyValueMapInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MaterialsProducerPropertyValueMapInput() {
    propertyValues_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MaterialsProducerPropertyValueMapInput();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerPropertyValueMapInput_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerPropertyValueMapInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput.class, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput.Builder.class);
  }

  public static final int MATERIALSPRODUCERID_FIELD_NUMBER = 1;
  private gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput materialsProducerId_;
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerIdInput materialsProducerId = 1;</code>
   * @return Whether the materialsProducerId field is set.
   */
  @java.lang.Override
  public boolean hasMaterialsProducerId() {
    return materialsProducerId_ != null;
  }
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerIdInput materialsProducerId = 1;</code>
   * @return The materialsProducerId.
   */
  @java.lang.Override
  public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput getMaterialsProducerId() {
    return materialsProducerId_ == null ? gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput.getDefaultInstance() : materialsProducerId_;
  }
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerIdInput materialsProducerId = 1;</code>
   */
  @java.lang.Override
  public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInputOrBuilder getMaterialsProducerIdOrBuilder() {
    return materialsProducerId_ == null ? gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput.getDefaultInstance() : materialsProducerId_;
  }

  public static final int PROPERTYVALUES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput> propertyValues_;
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
   */
  @java.lang.Override
  public java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput> getPropertyValuesList() {
    return propertyValues_;
  }
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInputOrBuilder> 
      getPropertyValuesOrBuilderList() {
    return propertyValues_;
  }
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
   */
  @java.lang.Override
  public int getPropertyValuesCount() {
    return propertyValues_.size();
  }
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
   */
  @java.lang.Override
  public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput getPropertyValues(int index) {
    return propertyValues_.get(index);
  }
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
   */
  @java.lang.Override
  public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInputOrBuilder getPropertyValuesOrBuilder(
      int index) {
    return propertyValues_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (materialsProducerId_ != null) {
      output.writeMessage(1, getMaterialsProducerId());
    }
    for (int i = 0; i < propertyValues_.size(); i++) {
      output.writeMessage(2, propertyValues_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (materialsProducerId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMaterialsProducerId());
    }
    for (int i = 0; i < propertyValues_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, propertyValues_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput)) {
      return super.equals(obj);
    }
    gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput other = (gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput) obj;

    if (hasMaterialsProducerId() != other.hasMaterialsProducerId()) return false;
    if (hasMaterialsProducerId()) {
      if (!getMaterialsProducerId()
          .equals(other.getMaterialsProducerId())) return false;
    }
    if (!getPropertyValuesList()
        .equals(other.getPropertyValuesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMaterialsProducerId()) {
      hash = (37 * hash) + MATERIALSPRODUCERID_FIELD_NUMBER;
      hash = (53 * hash) + getMaterialsProducerId().hashCode();
    }
    if (getPropertyValuesCount() > 0) {
      hash = (37 * hash) + PROPERTYVALUES_FIELD_NUMBER;
      hash = (53 * hash) + getPropertyValuesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerPropertyValueMapInput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerPropertyValueMapInput)
      gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerPropertyValueMapInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerPropertyValueMapInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput.class, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput.Builder.class);
    }

    // Construct using gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      materialsProducerId_ = null;
      if (materialsProducerIdBuilder_ != null) {
        materialsProducerIdBuilder_.dispose();
        materialsProducerIdBuilder_ = null;
      }
      if (propertyValuesBuilder_ == null) {
        propertyValues_ = java.util.Collections.emptyList();
      } else {
        propertyValues_ = null;
        propertyValuesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.Support.internal_static_gov_hhs_aspr_ms_gcm_taskit_protobuf_plugins_MaterialsProducerPropertyValueMapInput_descriptor;
    }

    @java.lang.Override
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput getDefaultInstanceForType() {
      return gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput.getDefaultInstance();
    }

    @java.lang.Override
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput build() {
      gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput buildPartial() {
      gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput result = new gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput result) {
      if (propertyValuesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          propertyValues_ = java.util.Collections.unmodifiableList(propertyValues_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.propertyValues_ = propertyValues_;
      } else {
        result.propertyValues_ = propertyValuesBuilder_.build();
      }
    }

    private void buildPartial0(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.materialsProducerId_ = materialsProducerIdBuilder_ == null
            ? materialsProducerId_
            : materialsProducerIdBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput) {
        return mergeFrom((gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput other) {
      if (other == gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput.getDefaultInstance()) return this;
      if (other.hasMaterialsProducerId()) {
        mergeMaterialsProducerId(other.getMaterialsProducerId());
      }
      if (propertyValuesBuilder_ == null) {
        if (!other.propertyValues_.isEmpty()) {
          if (propertyValues_.isEmpty()) {
            propertyValues_ = other.propertyValues_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePropertyValuesIsMutable();
            propertyValues_.addAll(other.propertyValues_);
          }
          onChanged();
        }
      } else {
        if (!other.propertyValues_.isEmpty()) {
          if (propertyValuesBuilder_.isEmpty()) {
            propertyValuesBuilder_.dispose();
            propertyValuesBuilder_ = null;
            propertyValues_ = other.propertyValues_;
            bitField0_ = (bitField0_ & ~0x00000002);
            propertyValuesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPropertyValuesFieldBuilder() : null;
          } else {
            propertyValuesBuilder_.addAllMessages(other.propertyValues_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMaterialsProducerIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput m =
                  input.readMessage(
                      gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput.parser(),
                      extensionRegistry);
              if (propertyValuesBuilder_ == null) {
                ensurePropertyValuesIsMutable();
                propertyValues_.add(m);
              } else {
                propertyValuesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput materialsProducerId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInputOrBuilder> materialsProducerIdBuilder_;
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerIdInput materialsProducerId = 1;</code>
     * @return Whether the materialsProducerId field is set.
     */
    public boolean hasMaterialsProducerId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerIdInput materialsProducerId = 1;</code>
     * @return The materialsProducerId.
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput getMaterialsProducerId() {
      if (materialsProducerIdBuilder_ == null) {
        return materialsProducerId_ == null ? gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput.getDefaultInstance() : materialsProducerId_;
      } else {
        return materialsProducerIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerIdInput materialsProducerId = 1;</code>
     */
    public Builder setMaterialsProducerId(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput value) {
      if (materialsProducerIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        materialsProducerId_ = value;
      } else {
        materialsProducerIdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerIdInput materialsProducerId = 1;</code>
     */
    public Builder setMaterialsProducerId(
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput.Builder builderForValue) {
      if (materialsProducerIdBuilder_ == null) {
        materialsProducerId_ = builderForValue.build();
      } else {
        materialsProducerIdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerIdInput materialsProducerId = 1;</code>
     */
    public Builder mergeMaterialsProducerId(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput value) {
      if (materialsProducerIdBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          materialsProducerId_ != null &&
          materialsProducerId_ != gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput.getDefaultInstance()) {
          getMaterialsProducerIdBuilder().mergeFrom(value);
        } else {
          materialsProducerId_ = value;
        }
      } else {
        materialsProducerIdBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerIdInput materialsProducerId = 1;</code>
     */
    public Builder clearMaterialsProducerId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      materialsProducerId_ = null;
      if (materialsProducerIdBuilder_ != null) {
        materialsProducerIdBuilder_.dispose();
        materialsProducerIdBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerIdInput materialsProducerId = 1;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput.Builder getMaterialsProducerIdBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMaterialsProducerIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerIdInput materialsProducerId = 1;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInputOrBuilder getMaterialsProducerIdOrBuilder() {
      if (materialsProducerIdBuilder_ != null) {
        return materialsProducerIdBuilder_.getMessageOrBuilder();
      } else {
        return materialsProducerId_ == null ?
            gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput.getDefaultInstance() : materialsProducerId_;
      }
    }
    /**
     * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerIdInput materialsProducerId = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInputOrBuilder> 
        getMaterialsProducerIdFieldBuilder() {
      if (materialsProducerIdBuilder_ == null) {
        materialsProducerIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerIdInputOrBuilder>(
                getMaterialsProducerId(),
                getParentForChildren(),
                isClean());
        materialsProducerId_ = null;
      }
      return materialsProducerIdBuilder_;
    }

    private java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput> propertyValues_ =
      java.util.Collections.emptyList();
    private void ensurePropertyValuesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        propertyValues_ = new java.util.ArrayList<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput>(propertyValues_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInputOrBuilder> propertyValuesBuilder_;

    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput> getPropertyValuesList() {
      if (propertyValuesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(propertyValues_);
      } else {
        return propertyValuesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public int getPropertyValuesCount() {
      if (propertyValuesBuilder_ == null) {
        return propertyValues_.size();
      } else {
        return propertyValuesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput getPropertyValues(int index) {
      if (propertyValuesBuilder_ == null) {
        return propertyValues_.get(index);
      } else {
        return propertyValuesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public Builder setPropertyValues(
        int index, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput value) {
      if (propertyValuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropertyValuesIsMutable();
        propertyValues_.set(index, value);
        onChanged();
      } else {
        propertyValuesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public Builder setPropertyValues(
        int index, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput.Builder builderForValue) {
      if (propertyValuesBuilder_ == null) {
        ensurePropertyValuesIsMutable();
        propertyValues_.set(index, builderForValue.build());
        onChanged();
      } else {
        propertyValuesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public Builder addPropertyValues(gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput value) {
      if (propertyValuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropertyValuesIsMutable();
        propertyValues_.add(value);
        onChanged();
      } else {
        propertyValuesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public Builder addPropertyValues(
        int index, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput value) {
      if (propertyValuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropertyValuesIsMutable();
        propertyValues_.add(index, value);
        onChanged();
      } else {
        propertyValuesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public Builder addPropertyValues(
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput.Builder builderForValue) {
      if (propertyValuesBuilder_ == null) {
        ensurePropertyValuesIsMutable();
        propertyValues_.add(builderForValue.build());
        onChanged();
      } else {
        propertyValuesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public Builder addPropertyValues(
        int index, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput.Builder builderForValue) {
      if (propertyValuesBuilder_ == null) {
        ensurePropertyValuesIsMutable();
        propertyValues_.add(index, builderForValue.build());
        onChanged();
      } else {
        propertyValuesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public Builder addAllPropertyValues(
        java.lang.Iterable<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput> values) {
      if (propertyValuesBuilder_ == null) {
        ensurePropertyValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, propertyValues_);
        onChanged();
      } else {
        propertyValuesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public Builder clearPropertyValues() {
      if (propertyValuesBuilder_ == null) {
        propertyValues_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        propertyValuesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public Builder removePropertyValues(int index) {
      if (propertyValuesBuilder_ == null) {
        ensurePropertyValuesIsMutable();
        propertyValues_.remove(index);
        onChanged();
      } else {
        propertyValuesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput.Builder getPropertyValuesBuilder(
        int index) {
      return getPropertyValuesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInputOrBuilder getPropertyValuesOrBuilder(
        int index) {
      if (propertyValuesBuilder_ == null) {
        return propertyValues_.get(index);  } else {
        return propertyValuesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public java.util.List<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInputOrBuilder> 
         getPropertyValuesOrBuilderList() {
      if (propertyValuesBuilder_ != null) {
        return propertyValuesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(propertyValues_);
      }
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput.Builder addPropertyValuesBuilder() {
      return getPropertyValuesFieldBuilder().addBuilder(
          gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput.getDefaultInstance());
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput.Builder addPropertyValuesBuilder(
        int index) {
      return getPropertyValuesFieldBuilder().addBuilder(
          index, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput.getDefaultInstance());
    }
    /**
     * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PropertyValueMapInput propertyValues = 2;</code>
     */
    public java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput.Builder> 
         getPropertyValuesBuilderList() {
      return getPropertyValuesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInputOrBuilder> 
        getPropertyValuesFieldBuilder() {
      if (propertyValuesBuilder_ == null) {
        propertyValuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInput.Builder, gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.properties.support.input.PropertyValueMapInputOrBuilder>(
                propertyValues_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        propertyValues_ = null;
      }
      return propertyValuesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerPropertyValueMapInput)
  }

  // @@protoc_insertion_point(class_scope:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerPropertyValueMapInput)
  private static final gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput();
  }

  public static gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MaterialsProducerPropertyValueMapInput>
      PARSER = new com.google.protobuf.AbstractParser<MaterialsProducerPropertyValueMapInput>() {
    @java.lang.Override
    public MaterialsProducerPropertyValueMapInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MaterialsProducerPropertyValueMapInput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MaterialsProducerPropertyValueMapInput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.MaterialsProducerPropertyValueMapInput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

