// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: materials/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input;

public interface MaterialsProducerIdInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.MaterialsProducerIdInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Any id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.google.protobuf.Any id = 1;</code>
   * @return The id.
   */
  com.google.protobuf.Any getId();
  /**
   * <code>.google.protobuf.Any id = 1;</code>
   */
  com.google.protobuf.AnyOrBuilder getIdOrBuilder();
}
