// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: materials/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input;

public interface StageIdInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.StageIdInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
