// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: materials/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input;

public interface StageBatchInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.StageBatchInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.StageIdInput stageId = 1;</code>
   * @return Whether the stageId field is set.
   */
  boolean hasStageId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.StageIdInput stageId = 1;</code>
   * @return The stageId.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.StageIdInput getStageId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.StageIdInput stageId = 1;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.StageIdInputOrBuilder getStageIdOrBuilder();

  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.BatchIdInput batchesInStage = 2;</code>
   */
  java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.BatchIdInput> 
      getBatchesInStageList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.BatchIdInput batchesInStage = 2;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.BatchIdInput getBatchesInStage(int index);
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.BatchIdInput batchesInStage = 2;</code>
   */
  int getBatchesInStageCount();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.BatchIdInput batchesInStage = 2;</code>
   */
  java.util.List<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.BatchIdInputOrBuilder> 
      getBatchesInStageOrBuilderList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.BatchIdInput batchesInStage = 2;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.BatchIdInputOrBuilder getBatchesInStageOrBuilder(
      int index);
}
