// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: materials/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input;

public interface StageInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.StageInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.StageIdInput stageId = 1;</code>
   * @return Whether the stageId field is set.
   */
  boolean hasStageId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.StageIdInput stageId = 1;</code>
   * @return The stageId.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.StageIdInput getStageId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.StageIdInput stageId = 1;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.materials.support.input.StageIdInputOrBuilder getStageIdOrBuilder();

  /**
   * <code>bool offered = 2;</code>
   * @return The offered.
   */
  boolean getOffered();
}
