// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: groups/data.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.data.input;

public interface GroupsPluginDataInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupsPluginDataInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupTypeIdInput groupTypeIds = 1;</code>
   */
  java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupTypeIdInput> 
      getGroupTypeIdsList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupTypeIdInput groupTypeIds = 1;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupTypeIdInput getGroupTypeIds(int index);
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupTypeIdInput groupTypeIds = 1;</code>
   */
  int getGroupTypeIdsCount();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupTypeIdInput groupTypeIds = 1;</code>
   */
  java.util.List<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupTypeIdInputOrBuilder> 
      getGroupTypeIdsOrBuilderList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupTypeIdInput groupTypeIds = 1;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupTypeIdInputOrBuilder getGroupTypeIdsOrBuilder(
      int index);

  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupInput groups = 2;</code>
   */
  java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupInput> 
      getGroupsList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupInput groups = 2;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupInput getGroups(int index);
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupInput groups = 2;</code>
   */
  int getGroupsCount();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupInput groups = 2;</code>
   */
  java.util.List<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupInputOrBuilder> 
      getGroupsOrBuilderList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupInput groups = 2;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupInputOrBuilder getGroupsOrBuilder(
      int index);

  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonToGroupMembershipInput personToGroupMemberships = 3;</code>
   */
  java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.PersonToGroupMembershipInput> 
      getPersonToGroupMembershipsList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonToGroupMembershipInput personToGroupMemberships = 3;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.PersonToGroupMembershipInput getPersonToGroupMemberships(int index);
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonToGroupMembershipInput personToGroupMemberships = 3;</code>
   */
  int getPersonToGroupMembershipsCount();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonToGroupMembershipInput personToGroupMemberships = 3;</code>
   */
  java.util.List<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.PersonToGroupMembershipInputOrBuilder> 
      getPersonToGroupMembershipsOrBuilderList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonToGroupMembershipInput personToGroupMemberships = 3;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.PersonToGroupMembershipInputOrBuilder getPersonToGroupMembershipsOrBuilder(
      int index);

  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupToPersonMembershipInput groupToPersonMemberships = 4;</code>
   */
  java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupToPersonMembershipInput> 
      getGroupToPersonMembershipsList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupToPersonMembershipInput groupToPersonMemberships = 4;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupToPersonMembershipInput getGroupToPersonMemberships(int index);
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupToPersonMembershipInput groupToPersonMemberships = 4;</code>
   */
  int getGroupToPersonMembershipsCount();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupToPersonMembershipInput groupToPersonMemberships = 4;</code>
   */
  java.util.List<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupToPersonMembershipInputOrBuilder> 
      getGroupToPersonMembershipsOrBuilderList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupToPersonMembershipInput groupToPersonMemberships = 4;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupToPersonMembershipInputOrBuilder getGroupToPersonMembershipsOrBuilder(
      int index);

  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupPropertyDefinitionMapInput groupPropertyDefinitions = 5;</code>
   */
  java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupPropertyDefinitionMapInput> 
      getGroupPropertyDefinitionsList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupPropertyDefinitionMapInput groupPropertyDefinitions = 5;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupPropertyDefinitionMapInput getGroupPropertyDefinitions(int index);
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupPropertyDefinitionMapInput groupPropertyDefinitions = 5;</code>
   */
  int getGroupPropertyDefinitionsCount();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupPropertyDefinitionMapInput groupPropertyDefinitions = 5;</code>
   */
  java.util.List<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupPropertyDefinitionMapInputOrBuilder> 
      getGroupPropertyDefinitionsOrBuilderList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupPropertyDefinitionMapInput groupPropertyDefinitions = 5;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupPropertyDefinitionMapInputOrBuilder getGroupPropertyDefinitionsOrBuilder(
      int index);

  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupPropertyValueMapInput groupPropertyValues = 6;</code>
   */
  java.util.List<gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupPropertyValueMapInput> 
      getGroupPropertyValuesList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupPropertyValueMapInput groupPropertyValues = 6;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupPropertyValueMapInput getGroupPropertyValues(int index);
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupPropertyValueMapInput groupPropertyValues = 6;</code>
   */
  int getGroupPropertyValuesCount();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupPropertyValueMapInput groupPropertyValues = 6;</code>
   */
  java.util.List<? extends gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupPropertyValueMapInputOrBuilder> 
      getGroupPropertyValuesOrBuilderList();
  /**
   * <code>repeated .gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupPropertyValueMapInput groupPropertyValues = 6;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupPropertyValueMapInputOrBuilder getGroupPropertyValuesOrBuilder(
      int index);

  /**
   * <code>int32 nextGroupIdValue = 7;</code>
   * @return The nextGroupIdValue.
   */
  int getNextGroupIdValue();
}
