name: Quarto Publish

on:
  push:
    branches: dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install ubuntu deps
        run: |
          sudo add-apt-repository 'deb http://mirrors.kernel.org/ubuntu focal-updates main'
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          libssl-dev \
          libcurl4-openssl-dev \
          unixodbc-dev \
          libxml2-dev \
          libmariadb-dev \
          libfontconfig1-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libfreetype6-dev \
          libpng-dev \
          libtiff5-dev \
          libjpeg-dev

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          working-directory: docgen

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docgen
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
