// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: groups/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input;

public interface GroupInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupIdInput groupId = 1;</code>
   * @return Whether the groupId field is set.
   */
  boolean hasGroupId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupIdInput groupId = 1;</code>
   * @return The groupId.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupIdInput getGroupId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupIdInput groupId = 1;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupIdInputOrBuilder getGroupIdOrBuilder();

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupTypeIdInput groupTypeId = 2;</code>
   * @return Whether the groupTypeId field is set.
   */
  boolean hasGroupTypeId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupTypeIdInput groupTypeId = 2;</code>
   * @return The groupTypeId.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupTypeIdInput getGroupTypeId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupTypeIdInput groupTypeId = 2;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupTypeIdInputOrBuilder getGroupTypeIdOrBuilder();
}
