// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: groups/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input;

public interface GroupPropertyDimensionInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupPropertyDimensionInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupIdInput groupId = 1;</code>
   * @return Whether the groupId field is set.
   */
  boolean hasGroupId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupIdInput groupId = 1;</code>
   * @return The groupId.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupIdInput getGroupId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupIdInput groupId = 1;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupIdInputOrBuilder getGroupIdOrBuilder();

  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupPropertyIdInput groupPropertyId = 2;</code>
   * @return Whether the groupPropertyId field is set.
   */
  boolean hasGroupPropertyId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupPropertyIdInput groupPropertyId = 2;</code>
   * @return The groupPropertyId.
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupPropertyIdInput getGroupPropertyId();
  /**
   * <code>.gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.GroupPropertyIdInput groupPropertyId = 2;</code>
   */
  gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input.GroupPropertyIdInputOrBuilder getGroupPropertyIdOrBuilder();

  /**
   * <code>repeated .google.protobuf.Any values = 3;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getValuesList();
  /**
   * <code>repeated .google.protobuf.Any values = 3;</code>
   */
  com.google.protobuf.Any getValues(int index);
  /**
   * <code>repeated .google.protobuf.Any values = 3;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .google.protobuf.Any values = 3;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Any values = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getValuesOrBuilder(
      int index);
}
