// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: groups/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input;

public interface PersonToGroupMembershipInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.PersonToGroupMembershipInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 personId = 1;</code>
   * @return The personId.
   */
  int getPersonId();

  /**
   * <code>repeated int32 groupIds = 2;</code>
   * @return A list containing the groupIds.
   */
  java.util.List<java.lang.Integer> getGroupIdsList();
  /**
   * <code>repeated int32 groupIds = 2;</code>
   * @return The count of groupIds.
   */
  int getGroupIdsCount();
  /**
   * <code>repeated int32 groupIds = 2;</code>
   * @param index The index of the element to return.
   * @return The groupIds at the given index.
   */
  int getGroupIds(int index);
}
