// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: groups/support.proto

package gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.groups.support.input;

public interface SimpleGroupTypeIdInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gov.hhs.aspr.ms.gcm.taskit.protobuf.plugins.SimpleGroupTypeIdInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
